version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Backend
      - "8081:8081" # Frontend
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
    command: npm run dev
